name: calculadora_bancario
description: "Conjuntos de ferramentas para cálculos financeiros."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  mask_text_input_formatter: ^2.8.0 
  intl: ^0.19.0
  http: ^1.2.0 
  url_launcher: ^6.2.4 
  xml2json: 
  flutter_widget_to_image: ^0.0.1
  share_plus: ^7.2.2
  google_mobile_ads: ^4.0.0
  loading_animation_widget: ^1.2.0+4
  google_fonts: ^6.1.0
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.4
  flutter_masked_text2: ^0.9.1
  flutter_native_splash: 
  flutter_launcher_icons: 
  flutter_app_name: 
  connectivity_wrapper: ^1.0.6
  provider: ^5.0.0
  sqflite: ^2.0.0+4
  
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#9FB9E3"
  image: assets/images/splash.png
  android: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter_app_name: 
  name: "Calculadora do Bancário"
  





flutter:


  uses-material-design: true


  assets:
    - assets/images/icons/
    - assets/images/

    
   