// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhe_man8qs3-w2JpLomDp7zhl3Y3o5Ugw',
    appId: '1:74344701501:web:99855fb426f9d79b1a5454',
    messagingSenderId: '74344701501',
    projectId: 'calculadora-do-bancario',
    authDomain: 'calculadora-do-bancario.firebaseapp.com',
    storageBucket: 'calculadora-do-bancario.appspot.com',
    measurementId: 'G-C25LYQR25L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh4C_n5ucm5ifFh398HN4v3L7iLUJIphI',
    appId: '1:74344701501:android:7868268e301d89431a5454',
    messagingSenderId: '74344701501',
    projectId: 'calculadora-do-bancario',
    storageBucket: 'calculadora-do-bancario.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2HyfdFm9Y6Jlj1OYgc5eEvNSZ-xbDyIE',
    appId: '1:74344701501:ios:a57a46a8bf0523aa1a5454',
    messagingSenderId: '74344701501',
    projectId: 'calculadora-do-bancario',
    storageBucket: 'calculadora-do-bancario.appspot.com',
    iosBundleId: 'br.com.danubioleite.calculadoraBancario',
  );
}
